apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "arju261997@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "gbrp zaii kioh ijgh"
type: Opaque

# Passw0rd@1234
